apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ytdl
  namespace: ytdl
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  rules:
    - host: ytdl.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ytdl
                port:
                  number: 80
