apiVersion: v1
kind: Secret
metadata:
  name: ytdl-secrets
  namespace: ytdl
type: Opaque
stringData:
  DATABASE_URL: "postgres://user:password@postgres-host:5432/ytdl"
  S3_ENDPOINT: "https://s3.us-east-1.amazonaws.com"
  S3_ACCESS_KEY: "CHANGEME"
  S3_SECRET_KEY: "CHANGEME"
